server.port: 8000
server.error.include-message: always
app:
  product-service:
    host: localhost
    port: 8001
  recommendation-service:
    host: localhost
    port: 8002
  review-service:
    host: localhost
    port: 8003
logging:
  level:
    root: INFO
    se.magnus: DEBUG
