#!/bin/sh
COMPOSE_FILE=./docker-compose-kafka.yml

docker-compose down --remove-orphans --rmi local -v && \
docker pull --platform=linux/amd64 mongo:3.6.23 && \
docker pull --platform=linux/amd64 mysql:5.7 && \
docker pull --platform=linux/arm64 wurstmeister/kafka:2.13-2.8.1 && \
docker pull --platform=amd64 wurstmeister/zookeeper:3.4.6 && \
./gradlew clean build --parallel && \
docker-compose -f ${COMPOSE_FILE} build && \
docker-compose -f ${COMPOSE_FILE} up -d && \
docker-compose -f ${COMPOSE_FILE} logs -f
