server.port: 8001
logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
